server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /app-config.js {
        root /usr/share/nginx/html;
        default_type application/javascript;
        add_header Cache-Control "no-store";
    }

    location /dicom-web {
    proxy_pass http://orthanc:8042;
    proxy_http_version 1.1;
    proxy_set_header Host orthanc:8042;
    }

    location /wado {
    proxy_pass http://orthanc:8042;
    proxy_http_version 1.1;
    proxy_set_header Host orthanc:8042;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
